### ISSUE TITLE
pallet_supersig Options

### ISSUE THREAD

**Issue by decentration** [kabocha-network/pallet_supersig#1]
# Master Beneficiary Option

Another option for supersig, is the "master beneficiary" option:

## The problem:

The problem is only 3 people in multisig sometimes it's hard to get someone to sign it quickly, but if you had 5 people then its more likely someone will sign your transaction quicker.

## Solution
The funds can go anywhere and be made by anyone, but IF the beneficiary signs it then only one other person needs to sign ELSE IF not beneficiary signs then there has to be a superMajority.

## More Explanation
The most common use for multisig is that there is really one owner and 2 signatories that provide extra security or “approves” transaction. The point of this most common use is that the final destination of the funds is for one Beneficiary. It’s not usually shared funds. 

The limitation with multisig, is that 2 other parties need to be trusted with not stealing the funds. It’s not a major problem with 2/3 multisg, but when we start to go to 2/4, 3/4, 2/5, 3/5, 2/6, 3/6, 4/6, 3/7, 4/7, etc multisigs it increase the risks of funds being taken from the Beneficiary.

Therefore to solve this problem, if the multisig could have a selected Master Beneficiary, and if that beneficary creates a transaction only one other signatory needs to sign. But if that person loses their signature a superMajority can release it.

**Comment by gdnathan** [comment]
work in progress on [this branch](https://github.com/rusty-crewmates/pallet_supersig/tree/feature--master-beneficiary)
